[package]
name = "signaldb-sdk"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
progenitor-client = { workspace = true }
reqwest.workspace = true
serde.workspace = true
