[package]
name = "compactor"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
common.workspace = true
datafusion.workspace = true
arrow-flight.workspace = true
object_store.workspace = true
iceberg-rust.workspace = true
tokio.workspace = true
futures.workspace = true
log.workspace = true
anyhow.workspace = true
async-trait.workspace = true
tracing.workspace = true
clap.workspace = true
uuid.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
env_logger.workspace = true

[[bin]]
name = "signaldb-compactor"
path = "src/main.rs"

[package.metadata.cargo-machete]
ignored = [
    "async-trait",
    "tracing",
    "arrow-flight",
    "chrono",
    "datafusion",
    "futures",
    "object_store",
    "serde",
    "serde_json",
    "uuid"
]
