name: Grafana Plugin - Create Plugin Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # Run once a month on the 1st day

# To use the default github token with the following elevated permissions make sure to check:
# **Allow GitHub Actions to create and approve pull requests** in repository settings > Actions.

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    name: Create Plugin Update
    uses: ./.github/workflows/grafana-plugin-cp-update-reusable.yml
    secrets: inherit
